# Generated by Django 4.1.13 on 2026-01-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('category', models.CharField(choices=[('WHEY', 'Whey Protein'), ('CREATINE', 'Creatine'), ('EAA', 'EAA / BCAA'), ('HEALTH', 'Vitamin & Khoáng chất')], max_length=20, verbose_name='Loại')),
                ('price', models.IntegerField(verbose_name='Giá tiền (VNĐ)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
    ]
