# Generated by Django 4.1.13 on 2026-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do từ chối đơn (nếu có)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPING', 'Đang giao hàng'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', '⛔ Đã bị từ chối')], default='PENDING', max_length=20),
        ),
    ]
