# Generated by Django 4.1.13 on 2026-01-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WHEY', 'Whey Protein'), ('CREATINE', 'Creatine'), ('EAA', 'EAA / BCAA'), ('HEALTH', 'Vitamin & Khoáng chất'), ('PRE', 'Pre-workout (Tăng sức mạnh)'), ('ACCESSORIES', 'Dụng cụ hỗ trợ tập luyện')], max_length=20, verbose_name='Loại'),
        ),
    ]
