# Generated by Django 4.1.13 on 2026-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên bài tập')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='exercises/videos/', verbose_name='Video/GIF hướng dẫn')),
                ('description', models.TextField(blank=True, verbose_name='Hướng dẫn chi tiết')),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Ngực'), ('BACK', 'Lưng/Xô'), ('LEGS', 'Chân/Mông'), ('SHOULDERS', 'Vai'), ('ARMS', 'Tay'), ('ABS', 'Bụng'), ('CARDIO', 'Tim mạch')], default='CHEST', max_length=50, verbose_name='Nhóm cơ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WHEY', 'Whey Protein'), ('CREATINE', 'Creatine'), ('EAA', 'EAA / BCAA'), ('HEALTH', 'Vitamin & Khoáng chất'), ('PRE', 'Pre-workout (Tăng sức mạnh)'), ('ACCESSORIES', 'Dụng cụ hỗ trợ tập luyện')], max_length=20, verbose_name='Loại'),
        ),
    ]
