# Generated by Django 4.1.13 on 2026-03-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_category'),
        ('store', '0006_exercise_alter_product_category'),
    ]

    operations = [
    ]
