# Generated by Django 4.1.13 on 2026-04-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_merge_20260325_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='exercises/videos/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Video (YouTube)'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Đã thanh toán'),
        ),
        migrations.AddField(
            model_name='product',
            name='import_price',
            field=models.IntegerField(default=0, verbose_name='Giá nhập (VNĐ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(verbose_name='Hướng dẫn chi tiết'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('CHEST', 'NGỰC'), ('BACK', 'LƯNG / XÔ'), ('LEGS', 'CHÂN / MÔNG'), ('SHOULDERS', 'VAI'), ('BICEPS', 'TAY TRƯỚC'), ('TRICEPS', 'TAY SAU'), ('ABS', 'BỤNG'), ('CARDIO', 'TIM MẠCH')], max_length=20, verbose_name='Nhóm cơ chính'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='exercises/videos/', verbose_name='Video bài tập (.mp4)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='Ảnh phụ'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product'),
        ),
    ]
