# Generated by Django 4.1.13 on 2026-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_title_exercise_name_exercise_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Giảm theo phần trăm (%)'), ('FIXED', 'Giảm theo số tiền cố định (VNĐ)')], default='FIXED', max_length=20, verbose_name='Loại giảm giá')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Đơn hàng tối thiểu')),
                ('valid_from', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('valid_to', models.DateTimeField(verbose_name='Ngày hết hạn')),
                ('active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Quản lý Mã giảm giá',
            },
        ),
    ]
