from .calculator import calculate_bmi, calculate_bmr, calculate_tdee
from .rules import bmi_category, calorie_by_goal


def recommend_plan(
    age,
    gender,
    height,
    weight,
    goal,
    activity_level="medium"
):
    bmi = calculate_bmi(height, weight)
    category = bmi_category(bmi)

    bmr = calculate_bmr(gender, height, weight, age)
    tdee = calculate_tdee(bmr, activity_level)
    calories = calorie_by_goal(tdee, goal)

    if goal == "gain_muscle":
        workout = "Push Pull Legs"
        diet = "High protein"
        schedule = "5 days/week"

    elif goal == "lose_weight":
        workout = "Cardio + Full Body"
        diet = "Low carb"
        schedule = "6 days/week"

    else:
        workout = "Full Body"
        diet = "Balanced"
        schedule = "3–4 days/week"

    return {
        "bmi": bmi,
        "body_category": category,
        "bmr": bmr,
        "tdee": tdee,
        "recommended_calories": calories,
        "workout_plan": workout,
        "diet": diet,
        "schedule": schedule,
        "note": "Generated by AI Coach (rule-based)"
    }
